desc: Flux

network_kwargs: 
    class_name: models.cogvideox.pipeline_cogvideox.CogVideoXSGPipeline.from_pretrained
    pretrained_model_name_or_path: THUDM/CogVideoX-5b
    torch_dtype: bfloat16
infer_kwargs:
    n_samples: 5                # number of generated videos for one prompt
    cfg_scale: 6                # CFG guidance scale
    pag_scale: 0                # Cogvideox doesn't use PAG
    sg_scale: 3                 # SG guidance scale
    sg_shift_scale: 10          # SG shift scale
    sg_type: sg_prev            # SG / SG_prev
    sg_prev_max_t: 500          # for t < sg_prev_max_t, we use sg_prev