desc: sd1_4

network_kwargs: 
    class_name: models.stable_diffusion.pipeline_sd.StableDiffusionSGPAGPipeline.from_pretrained
    pretrained_model_name_or_path: /storage/qiguojunLab/litiancheng/models/stable-diffusion-v1-4
    pag_applied_layers: mid

infer_kwargs:
    cfg_scale: 7.5              # CFG guidance scale
    pag_scale: 0.3              # PAG guidance scale
    sg_scale: 3                 # SG guidance scale
    sg_shift_scale: 10          # SG shift scale
    sg_type: sg_prev            # SG / SG_prev
    sg_prev_max_t: 500          # for t < sg_prev_max_t, we use sg_prev